import type { Metadata } from "next";
import { Geist, Geist_Mono, Manrope, Montserrat } from "next/font/google";
import "./globals.css";
import Navbar from "./containers/main-components/navbar";
import Footer from "./containers/main-components/footer";
import QualitySection from "./containers/main-components/quality-sec";
import Newsletter from "./containers/home-page/newsletter-sec";
import { CartProvider } from "./context/cartContext";
import { WishlistProvider } from "./context/wishlistContext";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "@/components/ui/sonner";

// Use next/font/google to optimize font loading
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
});

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} ${manrope.variable} ${montserrat.variable} antialiased`}
        >
          <Navbar />
          <CartProvider>
            <WishlistProvider>{children}</WishlistProvider>
          </CartProvider>
          <Toaster />
          <QualitySection />
          <Newsletter />
          <Footer />
        </body>
      </html>
    </ClerkProvider>
  );
}
